version: '3.5'
services:
  fastapi1:
    build: .
    ports:
      - 8000:8000
    environment:
      - user_db=postgres
      - database_db=postgres
      - host_db=postgres
      - password_db=changeme
      - port_db=5432
      - redis_url=redis://redis:6379/0
    depends_on:
      - postgres
    restart: on-failure      
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'
    networks:
      - appnet

  fastapi2:
    build: .
    ports:
      - 8001:8000    
    environment:
      - user_db=postgres
      - database_db=postgres
      - host_db=postgres
      - password_db=changeme
      - port_db=5432
      - redis_url=redis://redis:6379/0
    depends_on:
      - postgres
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'
    networks:
      - appnet

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi1
      - fastapi2
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
    networks:
      - appnet

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
          - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql        
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1GB'
    networks:
      - appnet

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - appnet
  #   command: redis-server --save "" --appendonly no --maxclients 10000
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: '0.5GB'

networks:
  appnet:
    driver: bridge
